In [8]:
from sklearn.preprocessing import Normalizer
from scipy.sparse import csr_matrix
import numpy as np
X = csr_matrix(np.array([[4, 1, 2, 2],
     [1, 3, 9, 3],
     [5, 7, 5, 1]]))

In [9]:
transformer = Normalizer(norm='l1')
transformer

Normalizer(norm='l1')

In [10]:

transformer.transform(X).sum(axis=1)


matrix([[1.],
        [1.],
        [1.]])

In [52]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfTransformer

In [42]:
# X is a mapping of user to document id, we require a csr_matrix with
# (user id, token id, token_weight) columns
X_transformed = self.input_transformer.transform(X)

# apply tfidf term frequencies to obtain a (user, token, tfidf_weight) sparse matrix
document = self.tfidf.transform(X_transformed)

# compute cosine sim with all documents
full_sim = sklearn.metrics.pairwise.cosine_similarity(self.documents, document, dense_output=False)

# sum cosine sim scores for each document
summed_scores = np.asarray(full_sim.sum(axis=1).reshape(-1))[0]

NameError: name 'self' is not defined

In [64]:
# TEST
# 1 user
# 3 items
# 4 tokens

item_vectors = np.array([[1, 0, 0, 1], [1, 1, 0, 1], [0, 0, 1, 1]])
user_vectors = np.array([[1, 0, 1]]).reshape((1, 3))

In [65]:
X_transformed = user_vectors @ item_vectors

In [66]:
X_transformed

array([[1, 0, 1, 2]])

In [67]:
tfidf = TfidfTransformer()
documents = tfidf.fit_transform(item_vectors)
documents.toarray()

array([[0.78980693, 0.        , 0.        , 0.61335554],
       [0.54783215, 0.72033345, 0.        , 0.42544054],
       [0.        , 0.        , 0.861037  , 0.50854232]])

In [68]:
document = tfidf.transform(X_transformed)
document.toarray()

array([[0.44102652, 0.        , 0.57989687, 0.68499287]])

In [69]:
full_sim = cosine_similarity(documents, document, dense_output=False)
full_sim.toarray()

array([[0.76846997],
       [0.53303224],
       [0.84766052]])

In [70]:
summed_scores = np.asarray(full_sim.sum(axis=1).reshape(-1))[0]
summed_scores

array([0.76846997, 0.53303224, 0.84766052])